version: '3.9'

services:
  mongo:
    container_name: mongo-db-dev
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "teste"
      MONGO_INITDB_ROOT_PASSWORD: "teste"
